# Numpy Python Library

In [25]:
import numpy as np

In [26]:
np.array([1,2,3])

array([1, 2, 3])

In [32]:
l = [[3,4,5], [1,2,3], [1,2,3]]
l

[[3, 4, 5], [1, 2, 3], [1, 2, 3]]

In [33]:
np.array(l)

array([[3, 4, 5],
       [1, 2, 3],
       [1, 2, 3]])

In [39]:
np.arange(50, 100, 5)

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [42]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [45]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [47]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [46]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [50]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
np.random.rand(5) #(0,1)

array([0.48101228, 0.23873622, 0.85617025, 0.5725066 , 0.77850209])

In [54]:
np.random.rand(5,5)

array([[0.25381545, 0.52433809, 0.08433518, 0.67294289, 0.18538711],
       [0.02398464, 0.25113139, 0.04049588, 0.05545128, 0.7169286 ],
       [0.78464409, 0.01091914, 0.15248404, 0.59448651, 0.18297911],
       [0.98576827, 0.36975923, 0.6499259 , 0.64088713, 0.80158849],
       [0.99722739, 0.17335745, 0.36966129, 0.88208822, 0.82327557]])

In [57]:
np.random.randn(10,5)

array([[-0.20052547, -0.55212959, -0.94390445,  1.94177256,  2.22195982],
       [ 0.34159269,  0.10690724,  0.53472584, -2.80790651, -0.86716258],
       [ 0.6240101 , -0.61782176,  1.72971401,  0.40813556,  0.09596414],
       [ 2.62235727,  0.29667148,  1.50213378, -0.27279425, -0.43503732],
       [-0.77027876,  0.06259152,  1.36611795,  1.34157722, -1.14957815],
       [ 1.04470488, -0.02423705,  0.35082109, -2.10186537, -0.38689039],
       [ 0.57755514, -1.31937201, -0.14139075,  0.21939718, -0.43829363],
       [-0.26794039,  0.93129594,  0.16565447, -0.14713295, -0.25959836],
       [-0.71713219,  0.00729229, -2.86663959,  0.11027295, -0.76483877],
       [-0.52251156, -1.23418588, -1.32511539,  0.15950685,  1.46173567]])

In [63]:
np.random.randint(50,100, 10)

array([90, 78, 52, 50, 95, 73, 72, 58, 62, 94])

In [70]:
arr = np.arange(30)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [66]:
arr1 = np.random.randint(0,100,10)

In [67]:
arr1

array([27, 80, 73, 79, 30, 63, 87, 91, 44, 67])

In [73]:
arr.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [74]:
arr1.max()

91

In [75]:
arr1.argmax()

7

In [76]:
arr1.min()

27

In [77]:
arr.argmin()

0

In [79]:
arr.shape

(30,)

In [80]:
arr = arr.reshape(5,6)

In [81]:
arr.shape

(5, 6)

In [82]:
arr = arr.reshape(10,3)

In [83]:
arr.shape

(10, 3)

In [84]:
type(arr)

numpy.ndarray

In [85]:
arr.dtype

dtype('int32')