# NumPy Indexing and Selection

In [1]:
import numpy as np

In [26]:
arr = np.arange(20)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
arr[:-5]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
arr[:5] = 100

In [29]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [30]:
slice_of_arr = arr[5:10].copy()

In [31]:
slice_of_arr[:] = 999

In [32]:
slice_of_arr

array([999, 999, 999, 999, 999])

In [33]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [34]:
l = [[1,2,3], [5,6,7], [7,8,9]]

In [35]:
arr = np.array(l)

In [36]:
arr

array([[1, 2, 3],
       [5, 6, 7],
       [7, 8, 9]])

In [42]:
arr[2][1]

8

In [59]:
arr

array([[1, 2, 3],
       [5, 6, 7],
       [7, 8, 9]])

In [62]:
arr[1:, 1:]

array([[6, 7],
       [8, 9]])

In [68]:
arr = np.zeros((10,10))

In [75]:
for i in range(len(arr)):
    arr[i] = i

In [ ]:
for i in 

In [76]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [77]:
arr[[3,5,7,8]]

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [78]:
arr = np.arange(1,11)

In [81]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [ ]:
ar